apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-app-backend
  template:
    metadata:
      labels:
        app: blog-app-backend
    spec:
      containers:
      - name: blog-app-backend
        image: kuldeep55567/blog-app-backend
        ports:
        - containerPort: 4500