version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
    environment:
      - DB=Blog
      - USER=admin
      - PASSWORD=iambad55567
      - HOST=database-2.cdcnj50cqiyf.ap-south-1.rds.amazonaws.com
      - DIALECT=mysql
      - PORT=4500
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: Blog
      MYSQL_USER: admin
      MYSQL_PASSWORD: iambad55567
    ports:
      - "3307:3306"
